### ISSUE TITLE
Problem: Scan offset, diode laser

### ISSUE THREAD

**Issue by xpozec** [bdring/FluidNC#603] opened 2022-09-10 11:15 UTC
### Controller Board

custom board 
![0-02-05-38d1237c79ea54a36d592164535c46b1fee4cea283a0e6ace16f848c96a21512_60751ca5bd221d9d](https://user-images.githubusercontent.com/113240530/189480421-73ccdf3f-916c-4eb5-87a6-c08763d0c4d0.jpg)

### Help From Board Vendor

- [ ] Yes
- [ ] No
- [X] Not Applicable

### Machine Description

Laser engraver, custom made. using A4988 stepper drivers, 7.5W diode laser
120W 12V power supply (meanwell) 
2 machines 
![0-02-05-0b1be2b94acf10e3f659d3d3a798d26d3c20839196d2cf725949c44a50c340bd_1ba36667f135bb32](https://user-images.githubusercontent.com/113240530/189480510-72a5fbc8-7441-45bd-a6ab-3e44c38e1b9a.jpg)
![0-02-05-7b34c6d5f02bd3267940940af512a705693d4c49b162badd1f0c403fac247337_ce3c029384992981](https://user-images.githubusercontent.com/113240530/189480513-61678ce8-1fe4-4585-8969-a9cd63c02a73.jpg)
![0-02-05-a961b846104c50ead516dbc7dbe2fd32a21b29abd2c43a0a69d83c0323986f95_f31ca68c48897119](https://user-images.githubusercontent.com/113240530/189480514-cb954d8f-c704-4277-8471-eacff656ff2f.jpg)

### Configuration file

```yaml
name: "Laser"
board: "Byte 4axis"

stepping:
  engine: RMT 
  idle_ms: 255
  dir_delay_us: 1
  pulse_us: 2
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: gpio.13:high
  
  x:
    steps_per_mm: 80
    max_rate_mm_per_min: 4800
    acceleration_mm_per_sec2: 1200
    max_travel_mm: 450
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 400.000
      seek_mm_per_min: 3000.000
      settle_ms: 250
      seek_scaler: 1.0
      feed_scaler: 1.0
    
    motor0:
      limit_neg_pin: gpio.34:low
      pulloff_mm: 3.000
      stepstick:
        direction_pin: gpio.2:low
        step_pin: gpio.0
    motor1:
      null_motor:

  y:
    steps_per_mm: 80
    max_rate_mm_per_min: 4800
    acceleration_mm_per_sec2: 1200
    max_travel_mm: 450
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 400.000
      seek_mm_per_min: 3000.000
      settle_ms: 250
      seek_scaler: 1.0
      feed_scaler: 1.0

    motor0:
      limit_neg_pin: gpio.35:low
      pulloff_mm: 3.000
      stepstick:
        direction_pin: gpio.15:high
        step_pin: gpio.26
    motor1:
      null_motor:

 
  # z:
  #   steps_per_mm: 2000
  #   max_rate_mm_per_min: 500
  #   acceleration_mm_per_sec2: 100
  #   max_travel_mm: 5
  #   homing:
  #     cycle: 0
  #     mpos_mm: 0
  #     positive_direction: false

  #   motor0:
  #     rc_servo:
  #       pwm_hz: 50
  #       output_pin: gpio.27
  #       min_pulse_us: 700
  #       max_pulse_us: 2200
        
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

coolant:
  flood_pin: NO_PIN
  mist_pin:  gpio.21

probe:
  pin: gpio.32:low:pu
  
Laser:
  pwm_hz: 5000
  output_pin: gpio.25
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 0
  speed_map: 0=0.000% 1000=100.000%
```

### Startup Messages

```text
no errors, all green
```

### User Interface Software

Lightburn, lasergrbl

### What happened?

Engraving over USB. 
There is some kind of strange  offset happening with 3.4.4
With new version, i am unable to test, as at this moment I am unable to home my machines, it only works like 20% of the time. 
when using Arduino board, or ESP32grbl (discontinued) it does not happen photos of those beautiful lades and Robbin Williams, done on the same machine arduino board and same board with ESP32grbl (discontinued), this rules out hardware issues i think
Engraving with 35mm/s 67% power
If you need any more information in order to be able to help, please ask, I will do my best to provide all.

### Other Information

![0-02-05-d1b65d2a9b2474b5d1e7c98a5ded6380a558e7338645264f46d4430d1f4fb76f_acb65ff8b3dd18fb](https://user-images.githubusercontent.com/113240530/189480563-fe22f3a2-6805-4d90-ace4-9adf1a85761b.jpg)
![0-02-05-f3899a727605d329ffa9b7c1a09d4ebdecd02495d01eed96b3e1d3cb2b1f148f_7b3f41154579e3ca](https://user-images.githubusercontent.com/113240530/189480568-08d3bf0b-1677-4d7c-8092-520f4584cfe4.jpg)
![0-02-05-ac0c16f893eb9e94c6adef493160a538725ae3b3f59f20294f6fffea0c8db663_1a19fc6f2b539999](https://user-images.githubusercontent.com/113240530/189480573-5f143298-4059-49ec-9f2a-5d2921586085.jpg)
![0-02-05-98f8f85ec1d62de3d71b9626dac435ff83156ca8ca863f81a078e276fc46d325_8e5147e8f8f9cc80](https://user-images.githubusercontent.com/113240530/189480577-1763a3fc-c37e-434b-aaad-8e54bf691213.jpg)

**Comment by xpozec** [comment] 2022-09-10 20:03
Did some more tests, as shown here: 
![0-02-05-86c9a2e5afc29e626bfe50e87721d248c541a133473a15df231311ed947ca425_c2bf49ab05c97043](https://user-images.githubusercontent.com/113240530/189499900-0444105d-6209-4457-8efe-032bc60611f8.jpg)
this is 0% overscaning, as i figured maybe this is the problem
![0-02-05-bfd8fa88f76583e77e5f3629885d9b0359f4815df117b669ae335c2ad2c9ec36_67b3a494c6043201](https://user-images.githubusercontent.com/113240530/189499905-c827fb7d-66b1-466b-85b0-34eb9a1d9eb6.jpg)
2% and 5%
![0-02-05-671a976a9f900d01af79981ccb9ee1f88f090597221fa3e252fc05e8578ab553_5ec0be062f1e9763](https://user-images.githubusercontent.com/113240530/189499944-dde00551-c382-4154-8f33-8f145bbe6481.jpg)
10% 15% 20%
![0-02-05-38cfa5a6449b25bdcc872713406963f9c40887af894d2b5dec79a3da4594e9a9_52238441938cfdde](https://user-images.githubusercontent.com/113240530/189499967-ce861d08-9f59-4902-84ef-fc7b2f197d85.jpg)
upper one was not  a bidirectional scan, only in one direction...
![0-02-05-a6cc3106e3ffdab77794072179d96bffbbbfca51b8b3a8c92a9285e90a5a098e_40ed391636f1bfbd](https://user-images.githubusercontent.com/113240530/189499979-af65b8a5-d80a-493f-8bb0-274e452273cf.jpg)
and finally bottom one was 90degree scan, as in not scan on x but on y axis 10% overscaning... 
best result was the unidirectional scan, but that was not perfect as well.

**Comment by MitchBradley** [comment] 2022-09-10 20:08
Can you do some simpler tests like gray rectangles?  I need a test case that is easy to reproduce and think about.  Looking at Daenerys Targaeryen is too distracting.

Also try saving the file and running it from an SD card.  Trying to eliminate variables.

**Comment by xpozec** [comment] 2022-09-10 20:17
Sure, it is night time now, i will conduct those tests, and post my results in about 12 hours from now i hope

**Comment by xpozec** [comment] 2022-09-11 10:38
update
ran a interval test in LB
so no fancy Targaeryens today 
![0-02-05-5fb12c2fd85c72f5cd200d89fb1c8aceb8c7a00f658fd9fc1b555065a441c78c_f2e0f7078c1d9560](https://user-images.githubusercontent.com/113240530/189522983-18efd016-20a8-4c60-9089-4b8776442f2e.jpg)
![0-02-05-60d3238d40154cebbb96dc1faf4bf06811591c3d3742e25395d627e35755dc43_4a520c3d9b9a4fdb](https://user-images.githubusercontent.com/113240530/189522986-9ed6f883-ba01-4510-85c1-8330183802fb.jpg)
![0-02-05-6f6bb659e659fdb2bf445f4907d9cfe7b43e1a45d6720633297b12cf0406fafb_4e931a620c6f6a22](https://user-images.githubusercontent.com/113240530/189522987-e4f1db4c-f936-4e99-9628-9fd98c7ff706.jpg)
![0-02-05-bf51e820fa1a2ace05a689e6fce9ffb8b64c2c846cdf7379e6ea86c42f4bf4fb_66c594015acd1cc7](https://user-images.githubusercontent.com/113240530/189522991-52f20ba5-d6f5-4be5-a629-ba344d323d1d.jpg)
the 0.05 is an overkill, and only looks ''good'' because it is an overburn same for 0.07
where a problem really shows is 0.20
this crosshatch and wavy result but as per photo only intermittently

**Comment by Avataar120** [comment] 2022-09-11 11:38
Hello,

Could you share your lightburn file (.lbrn2) please ?

I'd like to test on my setup

Thx

**Comment by xpozec** [comment] 2022-09-11 11:58
![Screenshot_10](https://user-images.githubusercontent.com/113240530/189526095-62bb7278-07b1-4ce0-9bd6-f48bbbad7da4.png)
LB does not allow me to save it as such, it is a laser tool, interval test, settings as per photo
I can save gcode file, not sure if that would help, but here it goes 
[test.zip](https://github.com/bdring/FluidNC/files/9542442/test.zip)

**Comment by Avataar120** [comment] 2022-09-11 13:55
Test on my side. 100mm/s - 10% power (K40)
It seems I don't have the same issue

![image](https://user-images.githubusercontent.com/12379002/189531295-32ce5082-9a67-4680-a7d0-afb2642ba991.png)

**Comment by xpozec** [comment] 2022-09-11 14:05
I am no expert, but does that . in 0.20 not look wrong to you? offset is bad at my side.
Is it me or am I seeing same or similar wavy pattern on your test as well 
I have 2 lasers for test, and both are giving me same results. My CO2 is not having these problems

**Comment by xpozec** [comment] 2022-09-12 10:38
more tests were performed: 
re compiled the GRBL esp32, same hardware. 
results:

**Comment by JHarding86** [comment] 2022-09-12 17:30
This looks like LightBurns scan offset adjustment. Base on how the .05 doesnt show the issue. That is because .05 steps are smaller than the width of the focal point of the laser. If you perform the scan offset adjustments as [show here](https://docs.lightburnsoftware.com/ScanningOffsetAdjustment.html), your issues should go away.

**Comment by xpozec** [comment] 2022-09-12 20:28
you are absolutely right about lightburn scanning offset , however another issue is the wavy lines this firmware produces, and the person doing the same test replicated the same problem.
Just because laser cuts well, does not mean it is doing a nice engraving, and diode lasers are all about photo engraving.
But here, lets say that I can fix the offset, how am I supposed to get rid of the miniature arcs, and non parallel lines?
I have a test in mind.
Discussing this with other people as well we have reached a conclusion that y motor is for some reason pulsing while x is scanning. I will run a cycle with oscilloscope in a day or 2, post my result here.
When it comes to scanning offset, having to adjust it on speed of 35mm/s is not something any other firmware required, I have a huge CO2 laser 1300x900mm and can achieve speeds of up to 900mm/s without need for scanning offset.
I found a similar issue in one of the closed issues, their solution was to use I2C stepper drivers, something I am unable to do.
I do however thank each and every person for looking in to my issue and taking the time to try and help

**Comment by MitchBradley** [comment] 2022-09-12 20:34
I am trying to duplicate the problem, while juggling about 5 other issues simultaneously.

**Comment by xpozec** [comment] 2022-09-12 20:38
@MitchBradley thank you, I am available to share more information and do some more tests if need be, I do posses oscilloscope and intermediate knowledge in both hardware and software design, maintenance and am a veteran at laser technologies. So if there is more information you need let me know, in the meantime i will keep using this topic as a sort of a blog of what was done to try to solve problem, and results I am getting if you dont mind, after all more data we all have, more likely we are to reach some sensible conclusion, cheers

**Comment by MitchBradley** [comment] 2022-09-12 20:41
Can you just try a single line to see if it is wavy?

**Comment by xpozec** [comment] 2022-09-13 10:00
![0-02-05-7d07709c3da22176e7958ba5893fcf7b2039c98855cc13924b126b3d6ec74404_a8abf3ac2add111a](https://user-images.githubusercontent.com/113240530/189872649-79b2646c-2c21-4e18-8aa2-7a7f882301de.jpg)
top one is esp32 grbl, bottom one is fluid nc, single line does not look like is an issue, some more tests will be performed today

**Comment by MitchBradley** [comment] 2022-09-13 16:13
Please attach the GCode file for the test above.

**Comment by xpozec** [comment] 2022-09-13 16:24
[test.zip](https://github.com/bdring/FluidNC/files/9558947/test.zip)

**Comment by MitchBradley** [comment] 2022-09-13 16:27
Try running that gcode file from SD card instead of streaming it from lightburn

**Comment by xpozec** [comment] 2022-09-13 16:39
I will install SD card reader, and let you know when I am done with tests

**Comment by MitchBradley** [comment] 2022-09-14 23:15
I converted an old EleksLaser gantry with a 2.5W laser to FluidNC by replacing the ancient EleksLaser Arduino Nano board with a [FYSETC E4 board](https://www.aliexpress.com/item/3256801518098396.html) that has TMC2209 drivers.  Here is the configuration file.  
[e4laser.yaml.txt](https://github.com/bdring/FluidNC/files/9570443/e4laser.yaml.txt)
The firmware is build from the[ StdFilesystem branch](https://github.com/bdring/FluidNC/tree/StdFilesystem).  Compared to v3.6.0, that branch has no changes that are relevant to motion or spindle/power control.
The laser is an old 2-pin one where the PWM is applied directly to the 12V power - not a "TTL PWM".  The E4 board's Extruder MOSFET switches the low side of the laser power on and off via PWM, with the high side of the laser connected directly to +12V.'

I edited your test file to remove the labels and engrave only 6 lines of the test pattern - since 6 lines is enough to show any systematic problems.  I also changed the distance between lines from 0.2 mm to 0.6 mm so the lines show up better and there is more Y travel to reveal any momentum issues.  I set the laser power to S300 which makes easy to read marks on yellow notepad paper without burning through.  Here is the file:
[test_small.gc.txt](https://github.com/bdring/FluidNC/files/9570468/test_small.gc.txt)
 I ran that file from SD using the WebUI Tablet UI.
Originally there was some waviness in the lines, but I was able to reduce it to a fairly small amount by dialing down the acceleration and making sure the gantry was square (the gantry has dual Y motors each with a separate driver).  Here are some runs:
![laser_tests_annotated](https://user-images.githubusercontent.com/4861133/190277370-1d73ed9b-8354-4394-a5a4-61346a2ba340.jpg)
* A100 SQ is acceleration=100 mm/sec2 with the gantry square.  I think the result is pretty good.
* A500 Sq is acceleration 500 mm/sec2 with the gantry square.  You can see some wobble (red arrows) due to the Y momentum still settling after the Y motion.
* A100 R1 is after I introduced some racking by pulling one end of the gantry manually by one step.  You can see some wobble (blue arrow) as the gantry tries to dissipate the mechanical stress.
* A100 R2 is the same; I pulled out out of square again by one step
In an earlier run - not shown - the gantry was badly racked and there was a significant amount of waviness.

**Comment by xpozec** [comment] 2022-09-15 08:22
Sure enough as soon as I reduced acceleration to 100 mm/sec2 wavy pattern was gone, however this is not good enough for engraving machines, not for the results, speeds etc that I am looking for. My machines have 1 y motor, and are shaft driven to the other end, this works perfectly and insures no skipping or any desync... 
If the ESP32 board and firmware gives out indication that it is the bottleneck on machines it is back to AVR boards, since Fluid NC can not handle fast raster, GRBL ESP32 randomly reports panicked core, sometimes after 10 min, sometimes after 12hours, ultimately ESP grbl ports are not there yet. 
Since I still have hardware, I will keep following the progress and do experiments as development moves forward.
Thank you guys 
![0-02-05-508753dfea239bbd369531784bbfc815b0e04c6a4c711ee466a40e027abd1c4a_7b9041d00e9cf2df](https://user-images.githubusercontent.com/113240530/190350871-cf9b2b59-f1de-4b1d-9848-a1624f70001b.jpg)

**Comment by MitchBradley** [comment] 2022-09-15 08:24
Closing since OP seems to be giving up.

**Closed by MitchBradley** 2022-09-15 08:24 UTC
