### ISSUE TITLE
Feature: Simple MPG Control for Jogging Machine

### ISSUE THREAD

**Issue by arlimbad222** [bdring/FluidNC#1403] opened 2024-12-12 09:42 UTC
### Machine Context

I would like to propose adding native support for a simple Manual Pulse Generator (MPG) control in FluidNC to enable precise and intuitive jogging of CNC machines. This feature is based on a custom implementation I developed using an ESP32, encoder, and custom PCB, but the current solution struggles with consistent accuracy in jogging commands. Native support for this functionality would greatly enhance usability for many FluidNC users.

### Feature Description

Description: I am requesting a feature to integrate simple MPG control directly into FluidNC for jogging CNC machines. This feature would enhance usability by allowing users to connect an MPG device for precise and intuitive machine jogging. I have developed a custom PCB and written a basic code for MPG-based jogging, but the current implementation lacks accuracy in jog commands. Native support in FluidNC could greatly improve performance and reliability.

Proposed Feature:

Add a native MPG interface in FluidNC to handle encoder signals for machine jogging.
Support customizable step sizes (e.g., 0.01, 0.1, 1.0 mm) based on an external selector switch.
Implement logic to process encoder ticks and translate them into accurate jog commands without delays or jerky movements.
Ensure proper handling of GRBL’s planner buffer to avoid overloading or causing the system to enter a hold state.
Use Case: This feature would be especially useful for:

Users working on custom CNC machines requiring precise manual jogging.
Developers integrating MPG devices into their setups without needing external microcontroller code.
Background: I have created a custom PCB designed for MPG control, with the following features:

A rotary encoder for position tracking.
Selector switches for axis selection and step size.
Integration with ESP32 via Serial2 for sending jog commands to FluidNC.
Challenges in Current Implementation:

Jog commands are not as accurate as expected, resulting in jerky movements.
The current workaround requires external code to manage encoder ticks and jog commands, which introduces delays and inconsistencies.
Planner buffer management is manual, making it difficult to achieve smooth operation.

i am using 2nd esp 32 for Communication  with fluidnc my main Communication protocol is bluetooth so i am using default tx-rx pin of esp32 with fluidnc i also try 2nd tx-rx but the reasult is same.

### Other Approaches

External Microcontroller for MPG Handling:

Using an external microcontroller (e.g., Arduino or another ESP32) to process encoder ticks and send jog commands to FluidNC via Serial or Bluetooth.
Challenges: Adds complexity to the setup, requires additional hardware, and can introduce latency or communication bottlenecks, especially when handling high-frequency encoder inputs.
Software-Based Workarounds:

Writing custom code to filter and process encoder signals, manage planner buffer states, and send optimized jog commands to FluidNC.
Challenges: Difficult to maintain and debug, especially when handling real-time communication over Bluetooth. Also, achieving perfect synchronization between encoder movement and jog commands is challenging without direct integration into FluidNC.
Use of External MPG-Compatible Firmware:

Replacing FluidNC with firmware that already supports MPG functionality natively.
Challenges: This requires abandoning FluidNC's rich feature set, which may not be a viable or desirable solution for most users.
Relying on Manual Jogging Through G-Code Senders:

Using a G-code sender to manually jog the machine through commands sent via USB or Bluetooth.
Challenges: Lacks the precision and intuitive control that an MPG provides, making it less suitable for tasks requiring fine control, like tool alignment or intricate machining setups.

### How I Can Help

Request: I would like FluidNC to natively:

Accept and process encoder input for jogging.
Automatically handle planner buffer management for smooth and accurate operation.
Provide debugging support for MPG integration.
Additional Resources: I can share the schematic of my custom PCB and my current code to provide context and support the development of this feature.

Thank you for considering this feature request. I believe it will add significant value to FluidNC and its user base.
[Schematic_MPG-INBULT-BOX_2024-12-12.pdf](https://github.com/user-attachments/files/18108890/Schematic_MPG-INBULT-BOX_2024-12-12.pdf)
[MPG CODE.txt](https://github.com/user-attachments/files/18108937/MPG.CODE.txt)
![image](https://github.com/user-attachments/assets/42949919-5ff4-41f0-a3d2-eca9748d27aa)
![image](https://github.com/user-attachments/assets/1eb64017-668c-4cf3-841f-0079786ee0d9)
![image](https://github.com/user-attachments/assets/b9434c19-d4ef-4866-8ebb-dfb472e9e76d)
![image](https://github.com/user-attachments/assets/83dfecc4-63f0-4c6c-b939-3a4b5d6bfafb)

**Comment by breiler** [comment] 2024-12-12 11:15
I think that the developers will be reluctant to add these types of features to the FluidNC core. It will add a more complexity and will be hard to maintain and support.

The way that you've implemented this by connecting to FluidNC through a secondary MCU through a serial channel is the preferred way to implement this and similar (successful) implementations has already been done with other hardware.

See this page for more information: http://wiki.fluidnc.com/en/hardware/official/M5Dial_Pendant

**Comment by bdring** [comment] 2024-12-12 13:46
A MPG (Manual Pulse Generator) is not something we would do. Sending step pulses directly to the motors without acceleration and deceleration control is likely to cause loss of accurate position.

We feel that our UART based pendants are quite good. We can support multiple types without constantly having to tweak the firmware.

![image](https://github.com/user-attachments/assets/ecf6c7a7-164d-466a-ad75-4c758513a5bc)

**Comment by bdring** [comment] 2024-12-12 13:50
BTW: A simple interface PCB costing less that $5 could adapt that device to FluidNC.

**Comment by arlimbad222** [comment] 2024-12-13 07:20
Addressing Developer Concerns and Proposal Justification
I understand that adding features like native MPG support to the FluidNC core might introduce additional complexity and maintenance challenges. However, I believe this proposal can be implemented in a way that keeps the codebase manageable while providing significant benefits to users. Here's why:

Simplicity Over Complexity:

The M5Dial Pendant is an excellent implementation but includes a display and additional features that may not be necessary for all users. My proposal focuses on using a standard MPG device that is widely available and straightforward to integrate, without requiring a display or complex setup.
Many users prefer a minimalistic, professional-grade solution for jogging, especially for tasks like tool alignment or manual movement of CNC axes.
Broad Market Availability:

Standard MPG devices are readily available in the market, making this solution highly accessible. Users won't need to custom-build hardware, 3D-print enclosures, or perform complex wiring setups. This lowers the barrier to entry and encourages more widespread adoption of FluidNC.
Open-Source Collaboration:

I am willing to share the PCB files and schematics for my MPG solution, making it an open-source project. This allows the community to adopt, adapt, and improve upon the design, creating a standardized and reliable solution for MPG-based jogging.
With community contributions, maintaining this feature can be collaborative, reducing the burden on core developers.
Professional and Intuitive Solution:

Adding support for a standard MPG in FluidNC provides a professional-grade alternative for users who don’t need a display or extra features but want a precise and intuitive way to control their CNC machines.
This aligns with the needs of users who prioritize simplicity and reliability in their setups.
Potential Implementation Approach:

The feature can be implemented as an optional module or plugin, reducing the impact on the core FluidNC code. Users who don't require MPG support won't be affected, while those who do can enable it with minimal configuration.
This modular approach addresses concerns about maintainability and complexity while still providing the functionality.
Filling a Gap in Current Offerings:

While secondary MCUs and existing implementations like the M5Dial Pendant are viable solutions, there is currently no standardized, easy-to-use MPG integration for FluidNC. This feature fills that gap and caters to a different segment of users.
Key Takeaway
By adding native MPG support for standard, market-available devices, FluidNC can offer a streamlined, open-source solution that lowers hardware complexity, encourages collaboration, and broadens its appeal to both hobbyists and professionals. The simplicity and accessibility of this approach make it a valuable addition to the ecosystem, complementing existing advanced options like the M5Dial Pendant.

I am not good at coding if  help me to code the esp the way you guys code the m5 dial we can add such a nice thing to fluidnc i dont want to change anything in fluidnc core code lets make one new mpg in fluidnc wiki i dont want to give you guys any stress just help me with the code ill test everything by my side i purchase almost everything for test and debug  i have 10 pcb set also.

I hope this perspective provides a compelling case for consideration. Let me know if you’d like further refinements!

![image](https://github.com/user-attachments/assets/ba45b210-d55c-4506-a30b-bad06a56e05e)

**Comment by bdring** [comment] 2024-12-13 13:32
So a CYD Pendant without the CYD?

**Comment by arlimbad222** [comment] 2024-12-13 14:42
I created the pcb, and I give my best to write a code I test lots of things but sadly I can't write good code for jogging. So my request is just write a simple code for us and I'll test everything then we will push new mpg open source both hardware and code so everyone can use simple mpg that available easily in market I run lots of machines like hass,jyoti etc.. and each and every machine has same simple mpg for jogging that's why I am thinking about it.

**Comment by MitchBradley** [comment] 2024-12-13 17:07
The routine "start_mpg_job()" from MultiJogScene.cpp in the FluidDial code is probably appropriate.  You would need to implement `selected(axis)` to read the axis switch and `distance(axis)` to read the units switch.

There should be no need for changes in the FluidNC core code.  We have many examples of jogging UI agents that work just fine with the existing serial communications methods.

**Comment by bdring** [comment] 2024-12-13 17:53
We are try to standardize on the RJ12 connector.

There are controllers, modules and adapters for that.

**Comment by arlimbad222** [comment] 2024-12-13 17:57
sure I'll change the pcb design accordingly one's I test things, currently I design simple 5.08mm pitch screw terminals( tx- rx- 5v- gnd) but I will learn from M5 dial and change the pcb design accordingly.

**Comment by MitchBradley** [comment] 2024-12-13 18:33
We are using plug-in connectors and off-the-shelf cables because we have found that, when people do their own wiring, they often make mistakes.  They destroy their electronics, then come onto Discord unhappy and ask us for help.  Despite your optimism about community contributions reducing the burden on core developers, we have found that just the opposite happens.  Every new feature or option results in more support requests than the community members are able to handle.  The number of sponsors is a small fraction of the total number of users, and the average sponsor contributes less than the cost of a simple meal.

**Comment by bdring** [comment] 2024-12-27 18:46
Closing this issue. This is not a bug or an enhancement to FluidNC. This would be a user created project.

**Closed by bdring** 2024-12-27 18:46 UTC
Labels: enhancement

**Comment by arlimbad222** [comment] 2024-12-27 19:14
I don't know if this is the right place to discuss this but if I sponsor this project or make a donation would you guys help me to code this kind of mpg,I am planning to become one of the sponsors for this project, I am in the middle of something and I am not good at coding I don't want to make it just for my self, if I successfully implement this mpg I'll share everything here,

 Please Don't get me wrong I just want to make it possible I already invest lots of time and effort so I cannot see this project dying and unfortunately my coding skills are not that much good.

Thank you for your response.

**Comment by bdring** [comment] 2024-12-27 21:52
I am not interested in helping anyone learn to code pendants at this time. You could offer a payment amount to see if you can hire someone. I would probably charge close to $1000 and would want to do my own version of the hardware.

**Comment by MitchBradley** [comment] 2024-12-29 04:45
How much were you thinking it should cost to get programming help of the type you need?

The FluidDial and CYD dial pendants can perform all of the functions (except e-stop) of your proposed MPG pendant, and many more such as probing, homing, DRO display, tool change and program control.  They can do everything that is required to run the machine for production use, whereas MPG only does jogging.  Their cost is dominated by the dial component and the cabling; the display+MCU add only about $10 to the cost.  The pendants are fairly popular and there has been very little if any demand for a de-featured MPG-only pendant, so I question the value that one would add to the ecosystem.  You seem convinced that it is important, but few others have echoed that sentiment.

The pendants do not have E-stop, but e-stop really should be a direct separately wired connection instead of running the function through the serial protocol, thus no software is needed for that function.  In fact, a truly-save e-stop should be directly wired to the motors and spindle so it stops them without software intervention.

**Comment by arlimbad222** [comment] 2025-06-18 20:03
Hi @MitchBradley 

I believe the cost would be around $200, but $1000 is currently out of my budget. I had taken a short break from this project due to other commitments, but now I’m fully focused on it again. If you're willing to help with the code, I can handle all the testing and also work on designing new hardware. I’m committed to making everything open source and contributing it back to the community.

**Comment by MitchBradley** [comment] 2025-06-18 20:14
$200 does not come close to paying for the time it would take me to do this work, nor for the additional support time to help naive users adopt it and ask why it doesn't work with random barely-documented variants they buy on AliExpress.

**Comment by arlimbad222** [comment] 2025-06-18 20:19
Hi @MitchBradley 
Totally understand - I really appreciate your honesty. I know your time is valuable and you're already contributing a lot to the ecosystem. I'll continue working on this independently and will share any progress or findings with the community. Thanks again for all the work you've done so far.

**Comment by MitchBradley** [comment] 2025-06-18 20:39
Your time would be better spent working on something that does not already have multiple supported, cost-effective solutions.
